language: java
sudo: false
jdk: oraclejdk8
script: "cd Code/ChroniclerJ/; mvn install"
after_success:
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\"><servers><server><id>jb.snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - cd $TRAVIS_BUILD_DIR/Code/ChroniclerJ; mvn deploy --settings ~/settings.xml
